import numpy as np
print("1-D ARRAY")
array_1d=np.array([[1,2,3,4]])
print(array_1d)
print("THE SIZE OF THE ARRAY")
print(array_1d.size)
print("THE SHAPE OF THE ARRAY")
print(array_1d.shape)
print("THE DATA USED IN THE ARRAY")
print(array_1d.dtype)
print("THE DIMENSIONS OF THE ARRAY")
print(array_1d.ndim)
print("")
print("2-D ARRAY")
array_2d=np.array([[1,2,3,4],[5,6,7,8]])
print(array_2d)
print("THE SIZE OF THE ARRAY")
print(array_2d.size)
print("THE SHAPE OF THE ARRAY")
print(array_2d.shape)
print("THE DATA USED IN THE ARRAY")
print(array_2d.dtype)
print("THE DIMENSIONS OF THE ARRAY")
print(array_2d.ndim)