name="     manu u know it's not easy to live without you   "
print(name.upper())
print(name.lower())
print(name.title())
print(name.count("a"))
print(name.title().replace(" ",""))
print(name.lstrip())
print(name.rstrip())
print(name.split())
print("THE LENGTH OF THE STRING,'NAME' IS:")
print(name.__len__())
print(len(name))
